baseURL = 'https://Hahahaxu.github.io/hugo_mork_data/'
languageCode = 'zh-cn'
title = 'Hahahaxu Wiki'
theme = 'PaperMod'

[params]
    env = "production"
    title = "Hahahaxu's Blog"
    description = "Backend Developer | Go | System Architect"
    # 日历样式: sakura | starry
    updateCalendarStyle = "sakura"

[params.assets]
    favicon = "favicon.svg"
    favicon16x16 = "favicon.svg"
    favicon32x32 = "favicon.svg"
    apple_touch_icon = "favicon.svg"
    safari_pinned_tab = "favicon.svg"

[params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 100
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
    identifier = "docs-hugo"
    name = "Hugo 搭建"
    url = "/docs/hugo搭建与发布/"
    weight = 5

[[menu.main]]
    identifier = "posts"
    name = "Archive"
    url = "/posts/"
    weight = 10
